### ISSUE TITLE
Readme.md Collection structure

### ISSUE THREAD

**Issue by VarakinMikhail** [studsovet/action_ddb#7]
actions: [*.action]
documents: [document]

Что здесь обозначают квадратные скобки, * и точка? Какие разделители между документами?

**Comment by WinstonMDP** [comment]
- [] означает список, то есть какое-то множество.
- \* подобно звёздочке в поиске файловой системы.
- . делит имя файла и его расширение.
- Документы не требуют разделителя в интерфейсе, так как нет команды добавить несколько документов сразу.
